In [1]:
import numpy
numpy.__version__

'2.2.0'

In [2]:
#list example
l=[[1,2],[3,4],[5,6]]
l_index=l[0]
l_index





[1, 2]

In [3]:
l_index[0]

1

In [4]:
l=[[[1],[2]],[[3],[4]],[[5],[6]]]
l_index=l[0]
l_index

[[1], [2]]

In [5]:
l[0][0][0]

1

In [6]:
l=list(range(0,12)) # it generate the particular value of the range  after typecasting thre range in the lists the number are clearly visible
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [7]:
arr = numpy.array(l)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
import numpy as np

arr = np.array(l)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
arr.shape

(12,)

In [11]:
# converting into 2 dimension
# fist represent number  of rows, second represent column
arr.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
arr.reshape((6,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [13]:
arr_3d=arr.reshape((3,4,1))
arr_3d

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [14]:
l1=arr_3d[2]
l1[1]

array([9])

In [15]:
print(l1[1][0])

9


In [16]:
arr_3d.ndim

3

>### Array
- 0D = 1
- 1D = [1]
- 2D = [[1]]
- 3D=[[[1]]]

In [17]:
# n=n-1 (dimension)